In [1]:
'''1) Create numpy array and perform following operation > Convert 1D array to 2D array'''
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

print("1D Array:")
print(arr_1d)

# Convert 1D array to 2D array (2 rows, 3 columns)
arr_2d = arr_1d.reshape(2, 3)

print("\n2D Array:")
print(arr_2d)

1D Array:
[1 2 3 4 5 6]

2D Array:
[[1 2 3]
 [4 5 6]]


In [2]:
'''Print Array Attributes(Like shape, dimenssion, data type, itemsize) '''
import numpy as np

# Create a NumPy array
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

# Print attributes
print("Array:")
print(arr)

print("\nShape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)
print("Item Size:", arr.itemsize, "bytes")

Array:
[[10 20 30]
 [40 50 60]]

Shape: (2, 3)
Dimensions: 2
Data Type: int64
Item Size: 8 bytes


In [4]:
'''Create a 3x3 NumPy array of all 9'''
import numpy as np

# Create a 3x3 array filled with 9
arr = np.full((3, 3), 9)

print(arr)


[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [5]:
'''Create a 1D array of 10 evenly spaced values between 25 and 125 '''
import numpy as np

# Create 10 evenly spaced values from 25 to 125
arr = np.linspace(25, 125, 10)

print(arr)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [6]:
'''Convert a Python list into a NumPy array'''
import numpy as np

# Python list
my_list = [10, 20, 30, 40, 50]

# Convert list to NumPy array
arr = np.array(my_list)

print("NumPy Array:")
print(arr)

NumPy Array:
[10 20 30 40 50]


In [7]:
''' Reverse a 1D NumPy array'''
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

reversed_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array:", reversed_arr)

Original Array: [1 2 3 4 5]
Reversed Array: [5 4 3 2 1]


In [8]:
'''Create a 4x4x3 array and extract value at its second set, first row and last column'''
import numpy as np

# Create a 4×4×3 array
arr = np.arange(1, 49).reshape(4, 4, 3)

print("Array:\n", arr)

# Extract value at second set, first row, last column
value = arr[1, 0, -1]

print("\nExtracted Value:", value)

Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]

Extracted Value: 15


In [9]:
''' Create a 4x4 and Extract Odd Rows and Even Columns '''
import numpy as np

# Create a 4×4 array
arr = np.arange(1, 17).reshape(4, 4)

print("Original Array:")
print(arr)

# Extract odd rows and even columns
result = arr[::2, 1::2]

print("\nOdd Rows and Even Columns:")
print(result)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Odd Rows and Even Columns:
[[ 2  4]
 [10 12]]


In [10]:
'''Slice the first two rows and first two columns of econd set from a 4x4x3 array'''
import numpy as np

# Create a 4×4×3 array
arr = np.arange(1, 49).reshape(4, 4, 3)

# Slice: second set, first two rows, first two columns
result = arr[1, :2, :2]

print("Sliced Array:")
print(result)

Sliced Array:
[[13 14]
 [16 17]]


In [11]:
''' Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]]'''
import numpy as np

# Create NumPy array
arr = np.array([[23, 56, 78, 93],
                [71, 82, 13, 24]])

# Replace odd numbers with -1 using for loop
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:
            arr[i][j] = -1

print(arr)

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [12]:
'''Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4]'''
import numpy as np

arr = np.array([1, 0, 2, 0, 3, 0, 4])

# Get indices of non-zero elements
indices = np.nonzero(arr)

print("Indices of non-zero elements:", indices)

Indices of non-zero elements: (array([0, 2, 4, 6]),)


In [13]:
''' Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element.'''
import numpy as np

# Create two arrays
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

# Addition
add = arr1 + arr2

# Subtraction
sub = arr1 - arr2

# Multiplication
mul = arr1 * arr2

# Division
div = arr1 / arr2

print("Array 1:", arr1)
print("Array 2:", arr2)

print("\nAddition:", add)
print("Subtraction:", sub)
print("Multiplication:", mul)
print("Division:", div)

Array 1: [10 20 30 40]
Array 2: [1 2 3 4]

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


In [14]:
'''Multiply two NumPy arrays element by element.'''
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Element-wise multiplication
result = arr1 * arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Multiplication Result:", result)

Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Multiplication Result: [ 5 12 21 32]


In [16]:
''' Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]'''
import numpy as np

arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

# Compute dot product
result = np.dot(arr1, arr2)

print("Dot Product:", result)

Dot Product: 1875
