In [1]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3])

# 2D array
arr2 = np.array([[4, 5, 6],
                 [7, 8, 9]])

# Convert 1D array to 2D and combine vertically
result = np.vstack((arr1, arr2))

print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
'''2) Flatten a 2d numpy array into 1d array '''
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flatten into 1D array
flat_arr = arr.flatten()

print("Original Array:")
print(arr)

print("\nFlattened Array:")
print(flat_arr)

Original Array:
[[1 2 3]
 [4 5 6]]

Flattened Array:
[1 2 3 4 5 6]


In [3]:
'''3) Reverse a numpy array'''
import numpy as np

# 1D array
arr1 = np.array([7, 8, 9])

# 2D array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Convert 1D to 2D and combine
combined = np.vstack((arr2, arr1))

print(combined)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
'''4) Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy'''
import numpy as np

# Create a 2D array
arr = np.array([[5, 10, 15],
                [20, 25, 30]])

print("Array:")
print(arr)

# Maximum value
print("\nMaximum Value:", np.max(arr))

# Minimum value
print("Minimum Value:", np.min(arr))

# Number of rows and columns
rows, cols = arr.shape
print("Rows:", rows)
print("Columns:", cols)

# Access all elements
print("\nAll Elements:")
for row in arr:
    for element in row:
        print(element, end=" ")
print()

# Access a specific element
print("\nSpecific Element at row 1, column 1:", arr[1, 1])

# Sum of all elements using for loop
total = 0
for row in arr:
    for element in row:
        total += element

print("Sum of Elements:", total)

# Create another array for arithmetic operations
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("\nSecond Array:")
print(arr2)

# Addition
print("\nAddition:")
print(arr + arr2)

# Subtraction
print("\nSubtraction:")
print(arr - arr2)

# Multiplication
print("\nMultiplication:")
print(arr * arr2)

# Division
print("\nDivision:")
print(arr / arr2)

Array:
[[ 5 10 15]
 [20 25 30]]

Maximum Value: 30
Minimum Value: 5
Rows: 2
Columns: 3

All Elements:
5 10 15 20 25 30 

Specific Element at row 1, column 1: 25
Sum of Elements: 105

Second Array:
[[1 2 3]
 [4 5 6]]

Addition:
[[ 6 12 18]
 [24 30 36]]

Subtraction:
[[ 4  8 12]
 [16 20 24]]

Multiplication:
[[  5  20  45]
 [ 80 125 180]]

Division:
[[5. 5. 5.]
 [5. 5. 5.]]


In [5]:
'''5) Iterate 3D array using for loop and nditer'''
import numpy as np

# Create a 3D array
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print("3D Array:")
print(arr)

# -----------------------------------
# 1. Iterate using nested for loops
# -----------------------------------
print("\nUsing for loops:")

for matrix in arr:
    for row in matrix:
        for element in row:
            print(element, end=" ")
print()

# -----------------------------------
# 2. Iterate using nditer()
# -----------------------------------
print("\nUsing np.nditer():")

for element in np.nditer(arr):
    print(element, end=" ")

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Using for loops:
1 2 3 4 5 6 7 8 9 10 11 12 

Using np.nditer():
1 2 3 4 5 6 7 8 9 10 11 12 

In [6]:
'''6) Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> Calculate average mean median mode values of two NumPy 2d-arrays'''
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [1, 2, 3]])

avg = (arr1 + arr2) / 2

combined = np.concatenate((arr1, arr2)).flatten()

print("Average:\n", avg)
print("Mean:", np.mean(combined))
print("Median:", np.median(combined))

# Mode
values, counts = np.unique(combined, return_counts=True)
mode = values[np.argmax(counts)]

print("Mode:", mode)

Average:
 [[4.  5.  6. ]
 [2.5 3.5 4.5]]
Mean: 4.25
Median: 3.5
Mode: 1
